// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-I6xch_w4Zzv1uRthfhc-zH_BGqL8Fa8',
    appId: '1:880658500084:web:33be60f36879b205ab51a1',
    messagingSenderId: '880658500084',
    projectId: 'first-app-c381f',
    authDomain: 'first-app-c381f.firebaseapp.com',
    databaseURL: 'https://first-app-c381f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-c381f.appspot.com',
    measurementId: 'G-0LX74BVJR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOdLhHZIEPk1o47CTNNJTVYQUiI-iE2Vk',
    appId: '1:880658500084:android:566bce8724ba5569ab51a1',
    messagingSenderId: '880658500084',
    projectId: 'first-app-c381f',
    databaseURL: 'https://first-app-c381f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-c381f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBySf3i3aYnJrocF2Wqfy9jqpgjz_UgvM8',
    appId: '1:880658500084:ios:36ec0c5502c5184fab51a1',
    messagingSenderId: '880658500084',
    projectId: 'first-app-c381f',
    databaseURL: 'https://first-app-c381f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-c381f.appspot.com',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBySf3i3aYnJrocF2Wqfy9jqpgjz_UgvM8',
    appId: '1:880658500084:ios:00f4fe8683e33029ab51a1',
    messagingSenderId: '880658500084',
    projectId: 'first-app-c381f',
    databaseURL: 'https://first-app-c381f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-c381f.appspot.com',
    iosBundleId: 'com.example.daftarBelanja.RunnerTests',
  );
}
